// This file is generated by Slice Machine. Update with care!

import Home from './Home';
import HomeArticle from './HomeArticle';

export {
	Home,
	HomeArticle,
};

export const components = {
	home: Home,
	home_article: HomeArticle,
};
