// This file is generated by Slice Machine. Update with care!

import Home from './Home';
import HomeArticle from './HomeArticle';
import PageHeading from './PageHeading';

export {
	Home,
	HomeArticle,
	PageHeading,
};

export const components = {
	home: Home,
	home_article: HomeArticle,
	page_heading: PageHeading,
};
